In [582]:
import numpy as np


def read_input(filename):
    with open(filename, 'r') as f:
        lines = f.readlines()

    for i in range(len(lines)):
        lines[i] = lines[i].replace("\n", "")

    first_line = lines[0].split(" ")
    first_line = [int(numeric_string) for numeric_string in first_line]
    n = first_line[0]
    m = first_line[1]

    genes = []
    for i in range(1, 1+n):
        line = lines[i].split(" ")
        line = [int(numeric_string) for numeric_string in line]
        genes.append(line)

    reads = []
    for i in range(1+n, 1+m+n):
        line = lines[i].split(" ")
        line = [int(numeric_string) for numeric_string in line]
        reads.append(line)

    return n, m, genes, reads


def calculateExpressions(filename):
    n, m, genes, reads = read_input(filename)

    intersectionsReads = []
    intersectionsGenes = []
    # Iterate over genes
    for i in range(n):
        # Iterate over each gene interval
        for j in range(0, len(genes[i]), 2):
            # Iterate over reads
            for k in range(m):
                # Iterate over each read interval
                for r in range(0, len(reads[k]), 2):
                    isLeftIn = reads[k][r] >= genes[i][j] and \
                        reads[k][r] <= genes[i][j+1]
                    isRightIn = reads[k][r + 1] >= genes[i][j] and \
                        reads[k][r+1] <= genes[i][j+1]
                    isIncluding = reads[k][r] <= genes[i][j] and \
                        reads[k][r + 1] >= genes[i][j+1]
                    if (isLeftIn or isRightIn or isIncluding):
                        intersectionsGenes.append(i)
                        intersectionsReads.append(k)

    reads = []
    for g in range(n):
        temp = []
        for r in range(len(intersectionsGenes)):
            if (intersectionsGenes[r] == g):
                temp.append(intersectionsReads[r])

        reads.append(np.unique(temp).tolist())

    readsOccurencesCounts = np.zeros(m)
    for i in range(m):
        for g in reads:
            if (g.__contains__(i)):
                readsOccurencesCounts[i] = readsOccurencesCounts[i]+1

    for i in range(m):
        if (readsOccurencesCounts[i] > 1):
            for r in reads:
                if (r.__contains__(i)):
                    r.remove(i)

    uniqueReadsPerGene = np.zeros(n)
    for i in range(n):
        uniqueReadsPerGene[i] = len(reads[i])

    return uniqueReadsPerGene


In [583]:
res = []
for i in range(1, 16, 1):
    res.append(calculateExpressions('./tests-easy/'+str(i)))
    print(res[i-1])


[2. 1.]
[0. 0.]
[0. 0. 0.]
[2. 0. 0. 0. 0. 0. 2. 2. 2. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[9.]
[39.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 9. 0. 0. 0. 0.]
[44.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.

In [589]:
res.append(calculateExpressions('./tests-easy/15'))
print(res[14])


[0. 0.]


In [594]:
for i in range(1, 16, 1):
    with open("./results/"+str(i), 'w') as f:
        for r in res[i-1]:
            f.write(str(int(r)) + '\n')


In [601]:
def read_console_input():
    in1 = input()
    first_line = in1.split(" ")
    first_line = [int(numeric_string) for numeric_string in first_line]
    n = first_line[0]
    m = first_line[1]

    genes = []
    for i in range(1, 1+n):
        l = input()
        line = l.split(" ")
        line = [int(numeric_string) for numeric_string in line]
        genes.append(line)

    reads = []
    for i in range(1+n, 1+m+n):
        l = input()
        line = l.split(" ")
        line = [int(numeric_string) for numeric_string in line]
        reads.append(line)

    return n, m, genes, reads

n, m, genes, reads = read_console_input()

2 4
[[1100, 1100, 2000, 2400], [3000, 3300]]
[[1100, 1160], [1190, 1200, 2000, 2050], [3280, 3300, 3500, 3550], [1500, 1560]]


In [ ]:
# Для Stepik

# put your python code here
import numpy as np


def read_console_input():
    in1 = input()
    first_line = in1.split(" ")
    first_line = [int(numeric_string) for numeric_string in first_line]
    n = first_line[0]
    m = first_line[1]

    genes = []
    for i in range(1, 1+n):
        l = input()
        line = l.split(" ")
        line = [int(numeric_string) for numeric_string in line]
        genes.append(line)

    reads = []
    for i in range(1+n, 1+m+n):
        l = input()
        line = l.split(" ")
        line = [int(numeric_string) for numeric_string in line]
        reads.append(line)

    return n, m, genes, reads


def calculateExpressions():
    n, m, genes, reads = read_console_input()

    intersectionsReads = []
    intersectionsGenes = []
    # Iterate over genes
    for i in range(n):
        # Iterate over each gene interval
        for j in range(0, len(genes[i]), 2):
            # Iterate over reads
            for k in range(m):
                # Iterate over each read interval
                for r in range(0, len(reads[k]), 2):
                    isLeftIn = reads[k][r] >= genes[i][j] and \
                        reads[k][r] <= genes[i][j+1]
                    isRightIn = reads[k][r + 1] >= genes[i][j] and \
                        reads[k][r+1] <= genes[i][j+1]
                    isIncluding = reads[k][r] <= genes[i][j] and \
                        reads[k][r + 1] >= genes[i][j+1]
                    if (isLeftIn or isRightIn or isIncluding):
                        intersectionsGenes.append(i)
                        intersectionsReads.append(k)

    reads = []
    for g in range(n):
        temp = []
        for r in range(len(intersectionsGenes)):
            if (intersectionsGenes[r] == g):
                temp.append(intersectionsReads[r])

        reads.append(np.unique(temp).tolist())

    readsOccurencesCounts = np.zeros(m)
    for i in range(m):
        for g in reads:
            if (g.__contains__(i)):
                readsOccurencesCounts[i] = readsOccurencesCounts[i]+1

    for i in range(m):
        if (readsOccurencesCounts[i] > 1):
            for r in reads:
                if (r.__contains__(i)):
                    r.remove(i)

    uniqueReadsPerGene = np.zeros(n)
    for i in range(n):
        uniqueReadsPerGene[i] = len(reads[i])

    return uniqueReadsPerGene


n, m, genes, reads = calculateExpressions()
